name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          if [ -d "tests" ]; then
            pytest
          else
            echo "No tests directory found, skipping tests."
          fi

      - name: Run Flask app
        run: |
          export FLASK_APP=app.py
          flask run --host=0.0.0.0 --port=5000 &
          sleep 5

      - name: Deploy to Heroku
        uses: w9jds/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: julianonyinye2025@gmail.com